---
  - name: First PAN 
    hosts: PAN
    connection: local
    gather_facts: no

    tasks:

    - name: show list of all interfaces
      panos_op:
        ip_address: "{{ ip_address }}"
        username: "{{ username }}"
        password: "{{ password }}"
        cmd: "show interface all"

    - name: show system info
      panos_op:
        ip_address: "{{ ip_address }}"
        username: "{{ username }}"
        password: "{{ password }}"
        cmd: "show system info"
      register: output
  
    - name: Print output
      debug:
        msg: "{{ output.stdout }}"


    - name: Configure
      panos_set:
        ip_address: "{{ ip_address }}"
        username: "{{ username }}"
        password: "{{ password }}"
        xpath: "/config/devices/entry[@name='localhost.localdomain']/network/interface/loopback/units/entry[@name='loopback.33']/ip"
        element: "<entry name='1.1.1.10/32'/>"
        xpath: "/config/devices/entry[@name='localhost.localdomain']/network/interface/loopback/units/entry[@name='loopback.34']/ip"
        element: "<entry name='1.1.1.20/32'/>"
        xpath: "/config/devices/entry[@name='localhost.localdomain']/network/interface/loopback/units/entry[@name='loopback.35']/ip"
        element: "<entry name='1.1.1.30/32'/>"
        xpath: "/config/devices/entry[@name='localhost.localdomain']/network/interface/loopback/units/entry[@name='loopback.36']/ip"
        element: "<entry name='1.1.1.40/32'/>"
        xpath: "/config/devices/entry[@name='localhost.localdomain']/network/interface/loopback/units/entry[@name='loopback.37']/ip"
        element: "<entry name='1.1.1.50/32'/>"
        xpath: "/config/devices/entry[@name='localhost.localdomain']/network/interface/loopback/units/entry[@name='loopback.38']/ip"
        element: "<entry name='1.1.1.60/32'/>"

    - name: Commit
      panos_commit:
        ip_address: "{{ ip_address }}"
        username: "{{ username }}"
        password: "{{ password }}"


        
         