---
  - name: First PAN 
    hosts: PAN
    connection: local
    gather_facts: no

    tasks:

    - name: show list of all interfaces
      panos_op:
        ip_address: '{{ ip_address }}'
        username: '{{ username }}'
        password: '{{ password }}'
        cmd: 'show interfaces all'

    - name: show system info
      panos_op:
        ip_address: '{{ ip_address }}'
        username: '{{ username }}'
        password: '{{ password }}'
        cmd: 'show system info'
        register: output
  
    - name: Print output
      debug:
        msg: '{{ output }}'